---
# ====== Application: Clinical Site Feasibility ==============
identification: 
  name: Clinical Site Feasibility
  alias: CLINICAL-SITE-FEASIBILITY
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 26819989760398149

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: TEAM25

globalization: 
  primary-language: English (en)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Clinical Site Feasibility

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 183 Push Notifications Credentials # 26843191229398371

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # AI Driven Clinical Site Feasibility

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 26820704504398158

navigation-bar: 
  implementation: List
  list: Navigation Bar # 26821929031398193
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: false

subscription: 
  version-number: 45087266960566

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Clinical Site Feasibility

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 26815429634398129
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 45013279515441

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 26815713259398134
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 45013279515509

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 26816099163398135
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 45013279515529

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 26816397908398136
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 45013279515548

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 26816659134398137
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 45013279515569

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 26816902780398138
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 45013279515590

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 26817282741398139
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 45013279515612

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 26817536114398140
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 45013279515636

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 26817817439398141
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 45013279515658

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 26818192562398142
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 45013279515696

- # ====== Component Setting: NATIVE_IR ========================
  id: 26818410573398143
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 45013279515737

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 26818781612398144
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 45013279515768

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 26819053207398145
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 45013279515795

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 26819374516398146
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 45013279515825

